// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_event (
  id, actor_user_id, country_id, action, target_type, target_id, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEventParams struct {
	ID          pgtype.UUID `json:"id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	CountryID   pgtype.UUID `json:"country_id"`
	Action      string      `json:"action"`
	TargetType  pgtype.Text `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.CountryID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
  e.id,
  u.display_name AS actor_name,
  e.action,
  c.code AS country_code,
  e.target_type,
  e.target_id,
  e.metadata,
  e.created_at
FROM audit_event e
JOIN app_user u ON u.id = e.actor_user_id
LEFT JOIN country c ON c.id = e.country_id
WHERE ($1::uuid IS NULL OR e.country_id = $1::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT 200
`

type ListAuditEventsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ActorName   string             `json:"actor_name"`
	Action      string             `json:"action"`
	CountryCode pgtype.Text        `json:"country_code"`
	TargetType  pgtype.Text        `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, dollar_1 pgtype.UUID) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorName,
			&i.Action,
			&i.CountryCode,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
