// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUserByTokenHash = `-- name: GetSessionUserByTokenHash :one
SELECT
  s.id AS session_id,
  s.expires_at,
  s.revoked_at,
  u.id AS user_id,
  u.email,
  u.display_name
FROM session s
JOIN app_user u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionUserByTokenHashRow struct {
	SessionID   pgtype.UUID        `json:"session_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) GetSessionUserByTokenHash(ctx context.Context, tokenHash string) (GetSessionUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionUserByTokenHash, tokenHash)
	var i GetSessionUserByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT country_id, role
FROM role_assignment
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

type ListRolesForUserRow struct {
	CountryID pgtype.UUID `json:"country_id"`
	Role      RoleCode    `json:"role"`
}

func (q *Queries) ListRolesForUser(ctx context.Context, userID pgtype.UUID) ([]ListRolesForUserRow, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesForUserRow
	for rows.Next() {
		var i ListRolesForUserRow
		if err := rows.Scan(&i.CountryID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE session
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const upsertMockUser = `-- name: UpsertMockUser :one
INSERT INTO app_user (id, email, display_name, auth_provider, provider_subject)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (auth_provider, provider_subject)
DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id, email, display_name, auth_provider, provider_subject, created_at
`

type UpsertMockUserParams struct {
	ID              pgtype.UUID `json:"id"`
	Email           string      `json:"email"`
	DisplayName     string      `json:"display_name"`
	AuthProvider    string      `json:"auth_provider"`
	ProviderSubject string      `json:"provider_subject"`
}

func (q *Queries) UpsertMockUser(ctx context.Context, arg UpsertMockUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, upsertMockUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AuthProvider,
		arg.ProviderSubject,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}
