// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaign (
  id, country_id, brand, title, reward_minor, currency, slots_total, slots_taken,
  status, platform, required_hashtag, brief
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, 'ACTIVE', $8, $9, $10)
RETURNING id, country_id, brand, title, reward_minor, currency, slots_total, slots_taken, status, platform, required_hashtag, brief, created_at, ends_at
`

type CreateCampaignParams struct {
	ID              pgtype.UUID `json:"id"`
	CountryID       pgtype.UUID `json:"country_id"`
	Brand           string      `json:"brand"`
	Title           string      `json:"title"`
	RewardMinor     int64       `json:"reward_minor"`
	Currency        string      `json:"currency"`
	SlotsTotal      int32       `json:"slots_total"`
	Platform        string      `json:"platform"`
	RequiredHashtag string      `json:"required_hashtag"`
	Brief           string      `json:"brief"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.CountryID,
		arg.Brand,
		arg.Title,
		arg.RewardMinor,
		arg.Currency,
		arg.SlotsTotal,
		arg.Platform,
		arg.RequiredHashtag,
		arg.Brief,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Brand,
		&i.Title,
		&i.RewardMinor,
		&i.Currency,
		&i.SlotsTotal,
		&i.SlotsTaken,
		&i.Status,
		&i.Platform,
		&i.RequiredHashtag,
		&i.Brief,
		&i.CreatedAt,
		&i.EndsAt,
	)
	return i, err
}

const createRewardRule = `-- name: CreateRewardRule :one
INSERT INTO reward_rule (
  id, campaign_id, trigger_type, pricing_type, flat_amount_minor, cap_type, cap_slots
)
VALUES ($1, $2, 'CONTENT_APPROVED', 'FLAT', $3, 'SLOTS_X_PRICE', $4)
RETURNING id, campaign_id, trigger_type, view_threshold, pricing_type, flat_amount_minor, percent_bps, cap_type, cap_slots, cap_pool_minor, created_at
`

type CreateRewardRuleParams struct {
	ID              pgtype.UUID `json:"id"`
	CampaignID      pgtype.UUID `json:"campaign_id"`
	FlatAmountMinor pgtype.Int8 `json:"flat_amount_minor"`
	CapSlots        pgtype.Int4 `json:"cap_slots"`
}

func (q *Queries) CreateRewardRule(ctx context.Context, arg CreateRewardRuleParams) (RewardRule, error) {
	row := q.db.QueryRow(ctx, createRewardRule,
		arg.ID,
		arg.CampaignID,
		arg.FlatAmountMinor,
		arg.CapSlots,
	)
	var i RewardRule
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TriggerType,
		&i.ViewThreshold,
		&i.PricingType,
		&i.FlatAmountMinor,
		&i.PercentBps,
		&i.CapType,
		&i.CapSlots,
		&i.CapPoolMinor,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignForCountry = `-- name: GetCampaignForCountry :one
SELECT id, country_id, brand, title, reward_minor, currency, slots_total, slots_taken, status, platform, required_hashtag, brief, created_at, ends_at
FROM campaign
WHERE id = $1 AND country_id = $2
`

type GetCampaignForCountryParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) GetCampaignForCountry(ctx context.Context, arg GetCampaignForCountryParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForCountry, arg.ID, arg.CountryID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Brand,
		&i.Title,
		&i.RewardMinor,
		&i.Currency,
		&i.SlotsTotal,
		&i.SlotsTaken,
		&i.Status,
		&i.Platform,
		&i.RequiredHashtag,
		&i.Brief,
		&i.CreatedAt,
		&i.EndsAt,
	)
	return i, err
}

const getRewardRuleByCampaignID = `-- name: GetRewardRuleByCampaignID :one
SELECT id, campaign_id, trigger_type, view_threshold, pricing_type, flat_amount_minor, percent_bps, cap_type, cap_slots, cap_pool_minor, created_at
FROM reward_rule
WHERE campaign_id = $1
`

func (q *Queries) GetRewardRuleByCampaignID(ctx context.Context, campaignID pgtype.UUID) (RewardRule, error) {
	row := q.db.QueryRow(ctx, getRewardRuleByCampaignID, campaignID)
	var i RewardRule
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TriggerType,
		&i.ViewThreshold,
		&i.PricingType,
		&i.FlatAmountMinor,
		&i.PercentBps,
		&i.CapType,
		&i.CapSlots,
		&i.CapPoolMinor,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCampaignsByCountry = `-- name: ListActiveCampaignsByCountry :many
SELECT id, country_id, brand, title, reward_minor, currency, slots_total, slots_taken, status, platform, required_hashtag, brief, created_at, ends_at
FROM campaign
WHERE country_id = $1 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveCampaignsByCountry(ctx context.Context, countryID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaignsByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Brand,
			&i.Title,
			&i.RewardMinor,
			&i.Currency,
			&i.SlotsTotal,
			&i.SlotsTaken,
			&i.Status,
			&i.Platform,
			&i.RequiredHashtag,
			&i.Brief,
			&i.CreatedAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByCountry = `-- name: ListCampaignsByCountry :many
SELECT id, country_id, brand, title, reward_minor, currency, slots_total, slots_taken, status, platform, required_hashtag, brief, created_at, ends_at
FROM campaign
WHERE country_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByCountry(ctx context.Context, countryID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Brand,
			&i.Title,
			&i.RewardMinor,
			&i.Currency,
			&i.SlotsTotal,
			&i.SlotsTaken,
			&i.Status,
			&i.Platform,
			&i.RequiredHashtag,
			&i.Brief,
			&i.CreatedAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
