// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimContentReview = `-- name: ClaimContentReview :one
UPDATE content_submission
SET
  state = $1::"SubmissionState",
  reject_reason = $2,
  reviewed_by = $3,
  reviewed_at = CURRENT_TIMESTAMP,
  row_version = row_version + 1
WHERE id = $4 AND state = 'SUBMITTED'
RETURNING id, participation_id, attempt_no, supersedes_id, url, platform, hashtag_ok, platform_ok, state, reject_reason, reviewed_by, reviewed_at, row_version, created_at
`

type ClaimContentReviewParams struct {
	NextState    SubmissionState `json:"next_state"`
	RejectReason pgtype.Text     `json:"reject_reason"`
	ReviewedBy   pgtype.UUID     `json:"reviewed_by"`
	ID           pgtype.UUID     `json:"id"`
}

// The conditional state predicate is the review claim: under concurrent approvals only one
// transaction can return a row. The loser observes zero rows after the winner commits.
func (q *Queries) ClaimContentReview(ctx context.Context, arg ClaimContentReviewParams) (ContentSubmission, error) {
	row := q.db.QueryRow(ctx, claimContentReview,
		arg.NextState,
		arg.RejectReason,
		arg.ReviewedBy,
		arg.ID,
	)
	var i ContentSubmission
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AttemptNo,
		&i.SupersedesID,
		&i.Url,
		&i.Platform,
		&i.HashtagOk,
		&i.PlatformOk,
		&i.State,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createContentSubmission = `-- name: CreateContentSubmission :one
INSERT INTO content_submission (
  id, participation_id, attempt_no, supersedes_id, url, platform,
  hashtag_ok, platform_ok, state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'SUBMITTED')
RETURNING id, participation_id, attempt_no, supersedes_id, url, platform, hashtag_ok, platform_ok, state, reject_reason, reviewed_by, reviewed_at, row_version, created_at
`

type CreateContentSubmissionParams struct {
	ID              pgtype.UUID `json:"id"`
	ParticipationID pgtype.UUID `json:"participation_id"`
	AttemptNo       int32       `json:"attempt_no"`
	SupersedesID    pgtype.UUID `json:"supersedes_id"`
	Url             string      `json:"url"`
	Platform        string      `json:"platform"`
	HashtagOk       bool        `json:"hashtag_ok"`
	PlatformOk      bool        `json:"platform_ok"`
}

func (q *Queries) CreateContentSubmission(ctx context.Context, arg CreateContentSubmissionParams) (ContentSubmission, error) {
	row := q.db.QueryRow(ctx, createContentSubmission,
		arg.ID,
		arg.ParticipationID,
		arg.AttemptNo,
		arg.SupersedesID,
		arg.Url,
		arg.Platform,
		arg.HashtagOk,
		arg.PlatformOk,
	)
	var i ContentSubmission
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AttemptNo,
		&i.SupersedesID,
		&i.Url,
		&i.Platform,
		&i.HashtagOk,
		&i.PlatformOk,
		&i.State,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createEarning = `-- name: CreateEarning :one
INSERT INTO earning (
  id, participation_id, submission_id, country_id, profile_id,
  gross_minor, tax_minor, currency, status, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'PENDING', CURRENT_TIMESTAMP)
RETURNING id, participation_id, submission_id, country_id, profile_id, gross_minor, tax_minor, currency, status, created_at, updated_at
`

type CreateEarningParams struct {
	ID              pgtype.UUID `json:"id"`
	ParticipationID pgtype.UUID `json:"participation_id"`
	SubmissionID    pgtype.UUID `json:"submission_id"`
	CountryID       pgtype.UUID `json:"country_id"`
	ProfileID       pgtype.UUID `json:"profile_id"`
	GrossMinor      int64       `json:"gross_minor"`
	TaxMinor        int64       `json:"tax_minor"`
	Currency        string      `json:"currency"`
}

func (q *Queries) CreateEarning(ctx context.Context, arg CreateEarningParams) (Earning, error) {
	row := q.db.QueryRow(ctx, createEarning,
		arg.ID,
		arg.ParticipationID,
		arg.SubmissionID,
		arg.CountryID,
		arg.ProfileID,
		arg.GrossMinor,
		arg.TaxMinor,
		arg.Currency,
	)
	var i Earning
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.SubmissionID,
		&i.CountryID,
		&i.ProfileID,
		&i.GrossMinor,
		&i.TaxMinor,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entry (
  id, country_id, profile_id, entry_type, amount_minor, currency,
  ref_type, ref_id, reversal_of_id, earning_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, country_id, profile_id, entry_type, amount_minor, currency, ref_type, ref_id, reversal_of_id, earning_id, created_at
`

type CreateLedgerEntryParams struct {
	ID           pgtype.UUID     `json:"id"`
	CountryID    pgtype.UUID     `json:"country_id"`
	ProfileID    pgtype.UUID     `json:"profile_id"`
	EntryType    LedgerEntryType `json:"entry_type"`
	AmountMinor  int64           `json:"amount_minor"`
	Currency     string          `json:"currency"`
	RefType      string          `json:"ref_type"`
	RefID        pgtype.UUID     `json:"ref_id"`
	ReversalOfID pgtype.UUID     `json:"reversal_of_id"`
	EarningID    pgtype.UUID     `json:"earning_id"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.ID,
		arg.CountryID,
		arg.ProfileID,
		arg.EntryType,
		arg.AmountMinor,
		arg.Currency,
		arg.RefType,
		arg.RefID,
		arg.ReversalOfID,
		arg.EarningID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.ProfileID,
		&i.EntryType,
		&i.AmountMinor,
		&i.Currency,
		&i.RefType,
		&i.RefID,
		&i.ReversalOfID,
		&i.EarningID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRejectedSubmission = `-- name: GetLatestRejectedSubmission :one
SELECT id, participation_id, attempt_no, supersedes_id, url, platform, hashtag_ok, platform_ok, state, reject_reason, reviewed_by, reviewed_at, row_version, created_at
FROM content_submission
WHERE participation_id = $1 AND state = 'REJECTED'
ORDER BY attempt_no DESC
LIMIT 1
`

func (q *Queries) GetLatestRejectedSubmission(ctx context.Context, participationID pgtype.UUID) (ContentSubmission, error) {
	row := q.db.QueryRow(ctx, getLatestRejectedSubmission, participationID)
	var i ContentSubmission
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AttemptNo,
		&i.SupersedesID,
		&i.Url,
		&i.Platform,
		&i.HashtagOk,
		&i.PlatformOk,
		&i.State,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipationForContent = `-- name: GetParticipationForContent :one
SELECT
  p.id, p.profile_id, p.campaign_id, p.country_id, p.state, p.joined_at, p.snapshot_reward_minor, p.snapshot_currency, p.snapshot_trigger_type, p.snapshot_pricing_type, p.row_version, p.fix_deadline_at, p.strike_count, p.submit_deadline_at, p.waitlisted_at,
  c.title AS campaign_title,
  c.platform AS campaign_platform,
  c.required_hashtag
FROM participation p
JOIN campaign c ON c.id = p.campaign_id
WHERE p.profile_id = $1 AND p.campaign_id = $2 AND p.country_id = $3
`

type GetParticipationForContentParams struct {
	ProfileID  pgtype.UUID `json:"profile_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
	CountryID  pgtype.UUID `json:"country_id"`
}

type GetParticipationForContentRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CampaignID          pgtype.UUID        `json:"campaign_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	State               ParticipationState `json:"state"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	RowVersion          int32              `json:"row_version"`
	FixDeadlineAt       pgtype.Timestamptz `json:"fix_deadline_at"`
	StrikeCount         int32              `json:"strike_count"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
	WaitlistedAt        pgtype.Timestamptz `json:"waitlisted_at"`
	CampaignTitle       string             `json:"campaign_title"`
	CampaignPlatform    string             `json:"campaign_platform"`
	RequiredHashtag     string             `json:"required_hashtag"`
}

func (q *Queries) GetParticipationForContent(ctx context.Context, arg GetParticipationForContentParams) (GetParticipationForContentRow, error) {
	row := q.db.QueryRow(ctx, getParticipationForContent, arg.ProfileID, arg.CampaignID, arg.CountryID)
	var i GetParticipationForContentRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
		&i.CampaignTitle,
		&i.CampaignPlatform,
		&i.RequiredHashtag,
	)
	return i, err
}

const getSubmissionForReviewCountry = `-- name: GetSubmissionForReviewCountry :one
SELECT
  s.id, s.participation_id, s.attempt_no, s.supersedes_id, s.url, s.platform, s.hashtag_ok, s.platform_ok, s.state, s.reject_reason, s.reviewed_by, s.reviewed_at, s.row_version, s.created_at,
  p.profile_id,
  p.country_id,
  p.snapshot_reward_minor,
  p.snapshot_currency
FROM content_submission s
JOIN participation p ON p.id = s.participation_id
WHERE s.id = $1 AND p.country_id = $2
`

type GetSubmissionForReviewCountryParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

type GetSubmissionForReviewCountryRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ParticipationID     pgtype.UUID        `json:"participation_id"`
	AttemptNo           int32              `json:"attempt_no"`
	SupersedesID        pgtype.UUID        `json:"supersedes_id"`
	Url                 string             `json:"url"`
	Platform            string             `json:"platform"`
	HashtagOk           bool               `json:"hashtag_ok"`
	PlatformOk          bool               `json:"platform_ok"`
	State               SubmissionState    `json:"state"`
	RejectReason        pgtype.Text        `json:"reject_reason"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	RowVersion          int32              `json:"row_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
}

func (q *Queries) GetSubmissionForReviewCountry(ctx context.Context, arg GetSubmissionForReviewCountryParams) (GetSubmissionForReviewCountryRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionForReviewCountry, arg.ID, arg.CountryID)
	var i GetSubmissionForReviewCountryRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AttemptNo,
		&i.SupersedesID,
		&i.Url,
		&i.Platform,
		&i.HashtagOk,
		&i.PlatformOk,
		&i.State,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RowVersion,
		&i.CreatedAt,
		&i.ProfileID,
		&i.CountryID,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
	)
	return i, err
}

const listContentQueue = `-- name: ListContentQueue :many
SELECT
  s.id AS submission_id,
  u.display_name AS creator_name,
  c.title AS campaign_title,
  s.url,
  s.attempt_no,
  s.hashtag_ok,
  s.platform_ok,
  s.created_at AS submitted_at
FROM content_submission s
JOIN participation p ON p.id = s.participation_id
JOIN creator_country_profile profile ON profile.id = p.profile_id
JOIN app_user u ON u.id = profile.user_id
JOIN campaign c ON c.id = p.campaign_id
WHERE s.state = 'SUBMITTED' AND p.country_id = $1
ORDER BY s.created_at ASC, s.id ASC
`

type ListContentQueueRow struct {
	SubmissionID  pgtype.UUID        `json:"submission_id"`
	CreatorName   string             `json:"creator_name"`
	CampaignTitle string             `json:"campaign_title"`
	Url           string             `json:"url"`
	AttemptNo     int32              `json:"attempt_no"`
	HashtagOk     bool               `json:"hashtag_ok"`
	PlatformOk    bool               `json:"platform_ok"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) ListContentQueue(ctx context.Context, countryID pgtype.UUID) ([]ListContentQueueRow, error) {
	rows, err := q.db.Query(ctx, listContentQueue, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentQueueRow
	for rows.Next() {
		var i ListContentQueueRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.CreatorName,
			&i.CampaignTitle,
			&i.Url,
			&i.AttemptNo,
			&i.HashtagOk,
			&i.PlatformOk,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentSubmissions = `-- name: ListContentSubmissions :many
SELECT id, participation_id, attempt_no, supersedes_id, url, platform, hashtag_ok, platform_ok, state, reject_reason, reviewed_by, reviewed_at, row_version, created_at
FROM content_submission
WHERE participation_id = $1
ORDER BY attempt_no DESC
`

func (q *Queries) ListContentSubmissions(ctx context.Context, participationID pgtype.UUID) ([]ContentSubmission, error) {
	rows, err := q.db.Query(ctx, listContentSubmissions, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentSubmission
	for rows.Next() {
		var i ContentSubmission
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AttemptNo,
			&i.SupersedesID,
			&i.Url,
			&i.Platform,
			&i.HashtagOk,
			&i.PlatformOk,
			&i.State,
			&i.RejectReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RowVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipationForContent = `-- name: LockParticipationForContent :one
SELECT
  p.id, p.profile_id, p.campaign_id, p.country_id, p.state, p.joined_at, p.snapshot_reward_minor, p.snapshot_currency, p.snapshot_trigger_type, p.snapshot_pricing_type, p.row_version, p.fix_deadline_at, p.strike_count, p.submit_deadline_at, p.waitlisted_at,
  c.title AS campaign_title,
  c.platform AS campaign_platform,
  c.required_hashtag
FROM participation p
JOIN campaign c ON c.id = p.campaign_id
WHERE p.profile_id = $1 AND p.campaign_id = $2 AND p.country_id = $3
FOR UPDATE OF p
`

type LockParticipationForContentParams struct {
	ProfileID  pgtype.UUID `json:"profile_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
	CountryID  pgtype.UUID `json:"country_id"`
}

type LockParticipationForContentRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CampaignID          pgtype.UUID        `json:"campaign_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	State               ParticipationState `json:"state"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	RowVersion          int32              `json:"row_version"`
	FixDeadlineAt       pgtype.Timestamptz `json:"fix_deadline_at"`
	StrikeCount         int32              `json:"strike_count"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
	WaitlistedAt        pgtype.Timestamptz `json:"waitlisted_at"`
	CampaignTitle       string             `json:"campaign_title"`
	CampaignPlatform    string             `json:"campaign_platform"`
	RequiredHashtag     string             `json:"required_hashtag"`
}

func (q *Queries) LockParticipationForContent(ctx context.Context, arg LockParticipationForContentParams) (LockParticipationForContentRow, error) {
	row := q.db.QueryRow(ctx, lockParticipationForContent, arg.ProfileID, arg.CampaignID, arg.CountryID)
	var i LockParticipationForContentRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
		&i.CampaignTitle,
		&i.CampaignPlatform,
		&i.RequiredHashtag,
	)
	return i, err
}

const markParticipationApproved = `-- name: MarkParticipationApproved :exec
UPDATE participation
SET state = 'APPROVED', row_version = row_version + 1
WHERE id = $1
`

func (q *Queries) MarkParticipationApproved(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParticipationApproved, id)
	return err
}

const markParticipationContentSubmitted = `-- name: MarkParticipationContentSubmitted :exec
UPDATE participation
SET state = 'CONTENT_SUBMITTED', row_version = row_version + 1
WHERE id = $1
`

func (q *Queries) MarkParticipationContentSubmitted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParticipationContentSubmitted, id)
	return err
}

const markParticipationRejected = `-- name: MarkParticipationRejected :exec
UPDATE participation
SET state = 'REJECTED', fix_deadline_at = $2, row_version = row_version + 1
WHERE id = $1
`

type MarkParticipationRejectedParams struct {
	ID            pgtype.UUID        `json:"id"`
	FixDeadlineAt pgtype.Timestamptz `json:"fix_deadline_at"`
}

func (q *Queries) MarkParticipationRejected(ctx context.Context, arg MarkParticipationRejectedParams) error {
	_, err := q.db.Exec(ctx, markParticipationRejected, arg.ID, arg.FixDeadlineAt)
	return err
}

const nextSubmissionAttemptNo = `-- name: NextSubmissionAttemptNo :one
SELECT (COALESCE(max(attempt_no), 0) + 1)::integer
FROM content_submission
WHERE participation_id = $1
`

func (q *Queries) NextSubmissionAttemptNo(ctx context.Context, participationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSubmissionAttemptNo, participationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
