// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: country.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT id, code, name, currency_code, currency_exponent, locale, fallback_locale, enabled, created_at
FROM country
WHERE code = $1
`

func (q *Queries) GetCountryByCode(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByCode, code)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CurrencyCode,
		&i.CurrencyExponent,
		&i.Locale,
		&i.FallbackLocale,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryConfigByCountryID = `-- name: GetCountryConfigByCountryID :one
SELECT id, country_id, tax_percent, min_payout_minor, feature_kyc, feature_payout, feature_cps, config_version, created_at, updated_at
FROM country_config
WHERE country_id = $1
`

func (q *Queries) GetCountryConfigByCountryID(ctx context.Context, countryID pgtype.UUID) (CountryConfig, error) {
	row := q.db.QueryRow(ctx, getCountryConfigByCountryID, countryID)
	var i CountryConfig
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.TaxPercent,
		&i.MinPayoutMinor,
		&i.FeatureKyc,
		&i.FeaturePayout,
		&i.FeatureCps,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreatorCountryProfiles = `-- name: ListCreatorCountryProfiles :many
SELECT
  p.id AS profile_id,
  p.onboarding_state,
  c.id AS country_id,
  c.code,
  c.name,
  c.currency_code,
  c.currency_exponent,
  c.locale,
  c.fallback_locale,
  c.enabled
FROM creator_country_profile p
JOIN country c ON c.id = p.country_id
WHERE p.user_id = $1
ORDER BY p.created_at ASC, p.id ASC
`

type ListCreatorCountryProfilesRow struct {
	ProfileID        pgtype.UUID `json:"profile_id"`
	OnboardingState  string      `json:"onboarding_state"`
	CountryID        pgtype.UUID `json:"country_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	CurrencyCode     string      `json:"currency_code"`
	CurrencyExponent int16       `json:"currency_exponent"`
	Locale           string      `json:"locale"`
	FallbackLocale   string      `json:"fallback_locale"`
	Enabled          bool        `json:"enabled"`
}

func (q *Queries) ListCreatorCountryProfiles(ctx context.Context, userID pgtype.UUID) ([]ListCreatorCountryProfilesRow, error) {
	rows, err := q.db.Query(ctx, listCreatorCountryProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatorCountryProfilesRow
	for rows.Next() {
		var i ListCreatorCountryProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.OnboardingState,
			&i.CountryID,
			&i.Code,
			&i.Name,
			&i.CurrencyCode,
			&i.CurrencyExponent,
			&i.Locale,
			&i.FallbackLocale,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreatorCountryProfile = `-- name: UpsertCreatorCountryProfile :one
INSERT INTO creator_country_profile (id, user_id, country_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, country_id)
DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, country_id, onboarding_state, created_at
`

type UpsertCreatorCountryProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) UpsertCreatorCountryProfile(ctx context.Context, arg UpsertCreatorCountryProfileParams) (CreatorCountryProfile, error) {
	row := q.db.QueryRow(ctx, upsertCreatorCountryProfile, arg.ID, arg.UserID, arg.CountryID)
	var i CreatorCountryProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CountryID,
		&i.OnboardingState,
		&i.CreatedAt,
	)
	return i, err
}
