// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: earnings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEarningsForDashboard = `-- name: ListEarningsForDashboard :many
SELECT
  e.id, e.participation_id, e.submission_id, e.country_id, e.profile_id, e.gross_minor, e.tax_minor, e.currency, e.status, e.created_at, e.updated_at,
  c.title AS campaign_title
FROM earning e
JOIN participation p ON p.id = e.participation_id
JOIN campaign c ON c.id = p.campaign_id
WHERE e.profile_id = $1 AND e.country_id = $2
ORDER BY e.created_at DESC, e.id DESC
`

type ListEarningsForDashboardParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

type ListEarningsForDashboardRow struct {
	ID              pgtype.UUID        `json:"id"`
	ParticipationID pgtype.UUID        `json:"participation_id"`
	SubmissionID    pgtype.UUID        `json:"submission_id"`
	CountryID       pgtype.UUID        `json:"country_id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	GrossMinor      int64              `json:"gross_minor"`
	TaxMinor        int64              `json:"tax_minor"`
	Currency        string             `json:"currency"`
	Status          EarningStatus      `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CampaignTitle   string             `json:"campaign_title"`
}

func (q *Queries) ListEarningsForDashboard(ctx context.Context, arg ListEarningsForDashboardParams) ([]ListEarningsForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listEarningsForDashboard, arg.ProfileID, arg.CountryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEarningsForDashboardRow
	for rows.Next() {
		var i ListEarningsForDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.SubmissionID,
			&i.CountryID,
			&i.ProfileID,
			&i.GrossMinor,
			&i.TaxMinor,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesForProfile = `-- name: ListLedgerEntriesForProfile :many
SELECT id, country_id, profile_id, entry_type, amount_minor, currency, ref_type, ref_id, reversal_of_id, earning_id, created_at
FROM ledger_entry
WHERE profile_id = $1 AND country_id = $2
ORDER BY
  created_at ASC,
  CASE entry_type
    WHEN 'EARNING_ACCRUE' THEN 10
    WHEN 'TAX' THEN 20
    WHEN 'PAYOUT_RESERVE' THEN 30
    WHEN 'PAYOUT_PAID' THEN 40
    WHEN 'PAYOUT_RELEASE' THEN 50
    WHEN 'REVERSAL' THEN 60
  END ASC,
  id ASC
`

type ListLedgerEntriesForProfileParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

// Ledger rows created in one PostgreSQL transaction share CURRENT_TIMESTAMP. The type rank keeps
// accrual before tax for a deterministic running balance, then falls back to UUID for total order.
func (q *Queries) ListLedgerEntriesForProfile(ctx context.Context, arg ListLedgerEntriesForProfileParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesForProfile, arg.ProfileID, arg.CountryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.ProfileID,
			&i.EntryType,
			&i.AmountMinor,
			&i.Currency,
			&i.RefType,
			&i.RefID,
			&i.ReversalOfID,
			&i.EarningID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
