// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: join.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWaitlistAhead = `-- name: CountWaitlistAhead :one
SELECT count(*)::bigint
FROM participation
WHERE campaign_id = $1
  AND state = 'WAITLISTED'
  AND waitlisted_at < $2
`

type CountWaitlistAheadParams struct {
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	WaitlistedAt pgtype.Timestamptz `json:"waitlisted_at"`
}

func (q *Queries) CountWaitlistAhead(ctx context.Context, arg CountWaitlistAheadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistAhead, arg.CampaignID, arg.WaitlistedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJoinedParticipation = `-- name: CreateJoinedParticipation :one
INSERT INTO participation (
  id, profile_id, campaign_id, country_id, state, joined_at,
  snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type,
  submit_deadline_at, fix_deadline_at, waitlisted_at
)
VALUES ($1, $2, $3, $4, 'JOINED', $5, $6, $7, $8, $9, $10, NULL, NULL)
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

type CreateJoinedParticipationParams struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CampaignID          pgtype.UUID        `json:"campaign_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
}

func (q *Queries) CreateJoinedParticipation(ctx context.Context, arg CreateJoinedParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, createJoinedParticipation,
		arg.ID,
		arg.ProfileID,
		arg.CampaignID,
		arg.CountryID,
		arg.JoinedAt,
		arg.SnapshotRewardMinor,
		arg.SnapshotCurrency,
		arg.SnapshotTriggerType,
		arg.SnapshotPricingType,
		arg.SubmitDeadlineAt,
	)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const createWaitlistedParticipation = `-- name: CreateWaitlistedParticipation :one
INSERT INTO participation (
  id, profile_id, campaign_id, country_id, state, waitlisted_at,
  snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type,
  submit_deadline_at, fix_deadline_at
)
VALUES ($1, $2, $3, $4, 'WAITLISTED', $5, NULL, NULL, NULL, NULL, NULL, NULL)
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

type CreateWaitlistedParticipationParams struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	CountryID    pgtype.UUID        `json:"country_id"`
	WaitlistedAt pgtype.Timestamptz `json:"waitlisted_at"`
}

func (q *Queries) CreateWaitlistedParticipation(ctx context.Context, arg CreateWaitlistedParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, createWaitlistedParticipation,
		arg.ID,
		arg.ProfileID,
		arg.CampaignID,
		arg.CountryID,
		arg.WaitlistedAt,
	)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const decrementCampaignSlots = `-- name: DecrementCampaignSlots :exec
UPDATE campaign
SET slots_taken = GREATEST(slots_taken - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementCampaignSlots(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementCampaignSlots, id)
	return err
}

const expireParticipation = `-- name: ExpireParticipation :one
UPDATE participation
SET state = 'EXPIRED', strike_count = strike_count + 1, row_version = row_version + 1
WHERE id = $1
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

func (q *Queries) ExpireParticipation(ctx context.Context, id pgtype.UUID) (Participation, error) {
	row := q.db.QueryRow(ctx, expireParticipation, id)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const getKycStateForProfile = `-- name: GetKycStateForProfile :one
SELECT state
FROM kyc_case
WHERE profile_id = $1
`

func (q *Queries) GetKycStateForProfile(ctx context.Context, profileID pgtype.UUID) (KycCaseState, error) {
	row := q.db.QueryRow(ctx, getKycStateForProfile, profileID)
	var state KycCaseState
	err := row.Scan(&state)
	return state, err
}

const getNextWaitlistedParticipation = `-- name: GetNextWaitlistedParticipation :one
SELECT id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
FROM participation
WHERE campaign_id = $1 AND state = 'WAITLISTED'
ORDER BY waitlisted_at ASC, id ASC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetNextWaitlistedParticipation(ctx context.Context, campaignID pgtype.UUID) (Participation, error) {
	row := q.db.QueryRow(ctx, getNextWaitlistedParticipation, campaignID)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const getParticipationByID = `-- name: GetParticipationByID :one
SELECT id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
FROM participation
WHERE id = $1
`

func (q *Queries) GetParticipationByID(ctx context.Context, id pgtype.UUID) (Participation, error) {
	row := q.db.QueryRow(ctx, getParticipationByID, id)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const getParticipationForJoin = `-- name: GetParticipationForJoin :one
SELECT id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
FROM participation
WHERE profile_id = $1 AND campaign_id = $2
`

type GetParticipationForJoinParams struct {
	ProfileID  pgtype.UUID `json:"profile_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) GetParticipationForJoin(ctx context.Context, arg GetParticipationForJoinParams) (Participation, error) {
	row := q.db.QueryRow(ctx, getParticipationForJoin, arg.ProfileID, arg.CampaignID)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const incrementCampaignSlots = `-- name: IncrementCampaignSlots :exec
UPDATE campaign
SET slots_taken = slots_taken + 1
WHERE id = $1
`

func (q *Queries) IncrementCampaignSlots(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementCampaignSlots, id)
	return err
}

const leaveParticipation = `-- name: LeaveParticipation :one
UPDATE participation
SET state = 'LEFT', waitlisted_at = NULL, row_version = row_version + 1
WHERE id = $1
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

func (q *Queries) LeaveParticipation(ctx context.Context, id pgtype.UUID) (Participation, error) {
	row := q.db.QueryRow(ctx, leaveParticipation, id)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const listExpiredParticipationCandidates = `-- name: ListExpiredParticipationCandidates :many
SELECT id, campaign_id
FROM participation
WHERE (state = 'JOINED' AND submit_deadline_at < $1)
   OR (state = 'REJECTED' AND fix_deadline_at < $1)
ORDER BY campaign_id ASC, id ASC
`

type ListExpiredParticipationCandidatesRow struct {
	ID         pgtype.UUID `json:"id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) ListExpiredParticipationCandidates(ctx context.Context, submitDeadlineAt pgtype.Timestamptz) ([]ListExpiredParticipationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredParticipationCandidates, submitDeadlineAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredParticipationCandidatesRow
	for rows.Next() {
		var i ListExpiredParticipationCandidatesRow
		if err := rows.Scan(&i.ID, &i.CampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyParticipations = `-- name: ListMyParticipations :many
SELECT
  p.id, p.profile_id, p.campaign_id, p.country_id, p.state, p.joined_at, p.snapshot_reward_minor, p.snapshot_currency, p.snapshot_trigger_type, p.snapshot_pricing_type, p.row_version, p.fix_deadline_at, p.strike_count, p.submit_deadline_at, p.waitlisted_at,
  c.title AS campaign_title,
  CASE WHEN p.state = 'WAITLISTED' THEN (
    SELECT count(*)::bigint + 1
    FROM participation ahead
    WHERE ahead.campaign_id = p.campaign_id
      AND ahead.state = 'WAITLISTED'
      AND ahead.waitlisted_at < p.waitlisted_at
  ) ELSE 0::bigint END AS waitlist_position
FROM participation p
JOIN campaign c ON c.id = p.campaign_id
WHERE p.profile_id = $1 AND p.country_id = $2 AND p.state <> 'LEFT'
ORDER BY p.joined_at DESC, p.id ASC
`

type ListMyParticipationsParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

type ListMyParticipationsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CampaignID          pgtype.UUID        `json:"campaign_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	State               ParticipationState `json:"state"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	RowVersion          int32              `json:"row_version"`
	FixDeadlineAt       pgtype.Timestamptz `json:"fix_deadline_at"`
	StrikeCount         int32              `json:"strike_count"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
	WaitlistedAt        pgtype.Timestamptz `json:"waitlisted_at"`
	CampaignTitle       string             `json:"campaign_title"`
	WaitlistPosition    int64              `json:"waitlist_position"`
}

func (q *Queries) ListMyParticipations(ctx context.Context, arg ListMyParticipationsParams) ([]ListMyParticipationsRow, error) {
	rows, err := q.db.Query(ctx, listMyParticipations, arg.ProfileID, arg.CountryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyParticipationsRow
	for rows.Next() {
		var i ListMyParticipationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.CampaignID,
			&i.CountryID,
			&i.State,
			&i.JoinedAt,
			&i.SnapshotRewardMinor,
			&i.SnapshotCurrency,
			&i.SnapshotTriggerType,
			&i.SnapshotPricingType,
			&i.RowVersion,
			&i.FixDeadlineAt,
			&i.StrikeCount,
			&i.SubmitDeadlineAt,
			&i.WaitlistedAt,
			&i.CampaignTitle,
			&i.WaitlistPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCampaignForJoin = `-- name: LockCampaignForJoin :one
SELECT
  c.id,
  c.country_id,
  c.title,
  c.reward_minor,
  c.currency,
  c.slots_total,
  c.slots_taken,
  c.status,
  c.ends_at,
  COALESCE(r.trigger_type, 'CONTENT_APPROVED'::"TriggerType") AS trigger_type,
  COALESCE(r.pricing_type, 'FLAT'::"PricingType") AS pricing_type
FROM campaign c
LEFT JOIN reward_rule r ON r.campaign_id = c.id
WHERE c.id = $1 AND c.country_id = $2
FOR UPDATE OF c
`

type LockCampaignForJoinParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

type LockCampaignForJoinRow struct {
	ID          pgtype.UUID        `json:"id"`
	CountryID   pgtype.UUID        `json:"country_id"`
	Title       string             `json:"title"`
	RewardMinor int64              `json:"reward_minor"`
	Currency    string             `json:"currency"`
	SlotsTotal  int32              `json:"slots_total"`
	SlotsTaken  int32              `json:"slots_taken"`
	Status      CampaignStatus     `json:"status"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	TriggerType TriggerType        `json:"trigger_type"`
	PricingType PricingType        `json:"pricing_type"`
}

func (q *Queries) LockCampaignForJoin(ctx context.Context, arg LockCampaignForJoinParams) (LockCampaignForJoinRow, error) {
	row := q.db.QueryRow(ctx, lockCampaignForJoin, arg.ID, arg.CountryID)
	var i LockCampaignForJoinRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Title,
		&i.RewardMinor,
		&i.Currency,
		&i.SlotsTotal,
		&i.SlotsTaken,
		&i.Status,
		&i.EndsAt,
		&i.TriggerType,
		&i.PricingType,
	)
	return i, err
}

const lockCampaignForReclaim = `-- name: LockCampaignForReclaim :one
SELECT
  c.id,
  c.country_id,
  c.title,
  c.reward_minor,
  c.currency,
  c.slots_total,
  c.slots_taken,
  c.status,
  c.ends_at,
  COALESCE(r.trigger_type, 'CONTENT_APPROVED'::"TriggerType") AS trigger_type,
  COALESCE(r.pricing_type, 'FLAT'::"PricingType") AS pricing_type
FROM campaign c
LEFT JOIN reward_rule r ON r.campaign_id = c.id
WHERE c.id = $1
FOR UPDATE OF c
`

type LockCampaignForReclaimRow struct {
	ID          pgtype.UUID        `json:"id"`
	CountryID   pgtype.UUID        `json:"country_id"`
	Title       string             `json:"title"`
	RewardMinor int64              `json:"reward_minor"`
	Currency    string             `json:"currency"`
	SlotsTotal  int32              `json:"slots_total"`
	SlotsTaken  int32              `json:"slots_taken"`
	Status      CampaignStatus     `json:"status"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	TriggerType TriggerType        `json:"trigger_type"`
	PricingType PricingType        `json:"pricing_type"`
}

func (q *Queries) LockCampaignForReclaim(ctx context.Context, id pgtype.UUID) (LockCampaignForReclaimRow, error) {
	row := q.db.QueryRow(ctx, lockCampaignForReclaim, id)
	var i LockCampaignForReclaimRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Title,
		&i.RewardMinor,
		&i.Currency,
		&i.SlotsTotal,
		&i.SlotsTaken,
		&i.Status,
		&i.EndsAt,
		&i.TriggerType,
		&i.PricingType,
	)
	return i, err
}

const nextWaitlistedAt = `-- name: NextWaitlistedAt :one
SELECT GREATEST(
  clock_timestamp(),
  COALESCE(max(waitlisted_at) + interval '1 millisecond', clock_timestamp())
)::timestamptz
FROM participation
WHERE campaign_id = $1 AND state = 'WAITLISTED'
`

// PostgreSQL stores waitlisted_at at millisecond precision. The campaign row lock serializes
// callers; advancing at least one millisecond avoids tied timestamps and preserves strict FCFS.
func (q *Queries) NextWaitlistedAt(ctx context.Context, campaignID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextWaitlistedAt, campaignID)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const updateJoinedParticipation = `-- name: UpdateJoinedParticipation :one
UPDATE participation
SET
  state = 'JOINED',
  joined_at = $2,
  snapshot_reward_minor = $3,
  snapshot_currency = $4,
  snapshot_trigger_type = $5,
  snapshot_pricing_type = $6,
  submit_deadline_at = $7,
  fix_deadline_at = NULL,
  waitlisted_at = NULL,
  row_version = row_version + 1
WHERE id = $1
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

type UpdateJoinedParticipationParams struct {
	ID                  pgtype.UUID        `json:"id"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
}

func (q *Queries) UpdateJoinedParticipation(ctx context.Context, arg UpdateJoinedParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, updateJoinedParticipation,
		arg.ID,
		arg.JoinedAt,
		arg.SnapshotRewardMinor,
		arg.SnapshotCurrency,
		arg.SnapshotTriggerType,
		arg.SnapshotPricingType,
		arg.SubmitDeadlineAt,
	)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}

const updateWaitlistedParticipation = `-- name: UpdateWaitlistedParticipation :one
UPDATE participation
SET
  state = 'WAITLISTED',
  waitlisted_at = $2,
  snapshot_reward_minor = NULL,
  snapshot_currency = NULL,
  snapshot_trigger_type = NULL,
  snapshot_pricing_type = NULL,
  submit_deadline_at = NULL,
  fix_deadline_at = NULL,
  row_version = row_version + 1
WHERE id = $1
RETURNING id, profile_id, campaign_id, country_id, state, joined_at, snapshot_reward_minor, snapshot_currency, snapshot_trigger_type, snapshot_pricing_type, row_version, fix_deadline_at, strike_count, submit_deadline_at, waitlisted_at
`

type UpdateWaitlistedParticipationParams struct {
	ID           pgtype.UUID        `json:"id"`
	WaitlistedAt pgtype.Timestamptz `json:"waitlisted_at"`
}

func (q *Queries) UpdateWaitlistedParticipation(ctx context.Context, arg UpdateWaitlistedParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, updateWaitlistedParticipation, arg.ID, arg.WaitlistedAt)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CampaignID,
		&i.CountryID,
		&i.State,
		&i.JoinedAt,
		&i.SnapshotRewardMinor,
		&i.SnapshotCurrency,
		&i.SnapshotTriggerType,
		&i.SnapshotPricingType,
		&i.RowVersion,
		&i.FixDeadlineAt,
		&i.StrikeCount,
		&i.SubmitDeadlineAt,
		&i.WaitlistedAt,
	)
	return i, err
}
