// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allKycFieldsAccepted = `-- name: AllKycFieldsAccepted :one
SELECT COALESCE(bool_and(state = 'ACCEPTED'), false)::boolean
FROM kyc_field
WHERE case_id = $1
`

func (q *Queries) AllKycFieldsAccepted(ctx context.Context, caseID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, allKycFieldsAccepted, caseID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createKycField = `-- name: CreateKycField :exec
INSERT INTO kyc_field (id, case_id, key, label, state)
VALUES ($1, $2, $3, $4, 'EMPTY')
ON CONFLICT (case_id, key) DO NOTHING
`

type CreateKycFieldParams struct {
	ID     pgtype.UUID `json:"id"`
	CaseID pgtype.UUID `json:"case_id"`
	Key    string      `json:"key"`
	Label  string      `json:"label"`
}

func (q *Queries) CreateKycField(ctx context.Context, arg CreateKycFieldParams) error {
	_, err := q.db.Exec(ctx, createKycField,
		arg.ID,
		arg.CaseID,
		arg.Key,
		arg.Label,
	)
	return err
}

const finishKycReview = `-- name: FinishKycReview :one
UPDATE kyc_case
SET state = $2, reviewed_by = $3, reviewed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, profile_id, state, reviewed_by, reviewed_at, created_at, updated_at
`

type FinishKycReviewParams struct {
	ID         pgtype.UUID  `json:"id"`
	State      KycCaseState `json:"state"`
	ReviewedBy pgtype.UUID  `json:"reviewed_by"`
}

func (q *Queries) FinishKycReview(ctx context.Context, arg FinishKycReviewParams) (KycCase, error) {
	row := q.db.QueryRow(ctx, finishKycReview, arg.ID, arg.State, arg.ReviewedBy)
	var i KycCase
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.State,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKycCaseByID = `-- name: GetKycCaseByID :one
SELECT id, profile_id, state, reviewed_by, reviewed_at, created_at, updated_at
FROM kyc_case
WHERE id = $1
`

func (q *Queries) GetKycCaseByID(ctx context.Context, id pgtype.UUID) (KycCase, error) {
	row := q.db.QueryRow(ctx, getKycCaseByID, id)
	var i KycCase
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.State,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKycCaseForCountry = `-- name: GetKycCaseForCountry :one
SELECT
  k.id,
  k.profile_id,
  k.state,
  p.country_id
FROM kyc_case k
JOIN creator_country_profile p ON p.id = k.profile_id
WHERE k.id = $1
FOR UPDATE OF k
`

type GetKycCaseForCountryRow struct {
	ID        pgtype.UUID  `json:"id"`
	ProfileID pgtype.UUID  `json:"profile_id"`
	State     KycCaseState `json:"state"`
	CountryID pgtype.UUID  `json:"country_id"`
}

func (q *Queries) GetKycCaseForCountry(ctx context.Context, id pgtype.UUID) (GetKycCaseForCountryRow, error) {
	row := q.db.QueryRow(ctx, getKycCaseForCountry, id)
	var i GetKycCaseForCountryRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.State,
		&i.CountryID,
	)
	return i, err
}

const listKycFields = `-- name: ListKycFields :many
SELECT id, case_id, key, label, value, state, reason
FROM kyc_field
WHERE case_id = $1
ORDER BY id ASC
`

func (q *Queries) ListKycFields(ctx context.Context, caseID pgtype.UUID) ([]KycField, error) {
	rows, err := q.db.Query(ctx, listKycFields, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KycField
	for rows.Next() {
		var i KycField
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Key,
			&i.Label,
			&i.Value,
			&i.State,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKycQueueCases = `-- name: ListKycQueueCases :many
SELECT
  k.id,
  k.profile_id,
  k.state,
  u.display_name AS creator_name,
  k.updated_at
FROM kyc_case k
JOIN creator_country_profile p ON p.id = k.profile_id
JOIN app_user u ON u.id = p.user_id
WHERE p.country_id = $1 AND k.state IN ('SUBMITTED', 'RESUBMITTED')
ORDER BY k.updated_at ASC, k.id ASC
`

type ListKycQueueCasesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	State       KycCaseState       `json:"state"`
	CreatorName string             `json:"creator_name"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListKycQueueCases(ctx context.Context, countryID pgtype.UUID) ([]ListKycQueueCasesRow, error) {
	rows, err := q.db.Query(ctx, listKycQueueCases, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKycQueueCasesRow
	for rows.Next() {
		var i ListKycQueueCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.State,
			&i.CreatorName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewKycField = `-- name: ReviewKycField :exec
UPDATE kyc_field
SET state = $3, reason = $4
WHERE case_id = $1 AND key = $2
`

type ReviewKycFieldParams struct {
	CaseID pgtype.UUID   `json:"case_id"`
	Key    string        `json:"key"`
	State  KycFieldState `json:"state"`
	Reason pgtype.Text   `json:"reason"`
}

func (q *Queries) ReviewKycField(ctx context.Context, arg ReviewKycFieldParams) error {
	_, err := q.db.Exec(ctx, reviewKycField,
		arg.CaseID,
		arg.Key,
		arg.State,
		arg.Reason,
	)
	return err
}

const submitKycCase = `-- name: SubmitKycCase :one
UPDATE kyc_case
SET
  state = CASE WHEN state = 'REJECTED' THEN 'RESUBMITTED'::"KycCaseState" ELSE 'SUBMITTED'::"KycCaseState" END,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, profile_id, state, reviewed_by, reviewed_at, created_at, updated_at
`

func (q *Queries) SubmitKycCase(ctx context.Context, id pgtype.UUID) (KycCase, error) {
	row := q.db.QueryRow(ctx, submitKycCase, id)
	var i KycCase
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.State,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEditableKycField = `-- name: UpdateEditableKycField :exec
UPDATE kyc_field
SET value = $3, state = 'FILLED', reason = NULL
WHERE case_id = $1 AND key = $2 AND state <> 'ACCEPTED'
`

type UpdateEditableKycFieldParams struct {
	CaseID pgtype.UUID `json:"case_id"`
	Key    string      `json:"key"`
	Value  pgtype.Text `json:"value"`
}

func (q *Queries) UpdateEditableKycField(ctx context.Context, arg UpdateEditableKycFieldParams) error {
	_, err := q.db.Exec(ctx, updateEditableKycField, arg.CaseID, arg.Key, arg.Value)
	return err
}

const upsertKycCase = `-- name: UpsertKycCase :one
INSERT INTO kyc_case (id, profile_id, state, updated_at)
VALUES ($1, $2, 'DRAFT', CURRENT_TIMESTAMP)
ON CONFLICT (profile_id)
DO UPDATE SET profile_id = EXCLUDED.profile_id
RETURNING id, profile_id, state, reviewed_by, reviewed_at, created_at, updated_at
`

type UpsertKycCaseParams struct {
	ID        pgtype.UUID `json:"id"`
	ProfileID pgtype.UUID `json:"profile_id"`
}

func (q *Queries) UpsertKycCase(ctx context.Context, arg UpsertKycCaseParams) (KycCase, error) {
	row := q.db.QueryRow(ctx, upsertKycCase, arg.ID, arg.ProfileID)
	var i KycCase
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.State,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
