// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchStatus string

const (
	BatchStatusOPEN   BatchStatus = "OPEN"
	BatchStatusLOCKED BatchStatus = "LOCKED"
)

func (e *BatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStatus(s)
	case string:
		*e = BatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStatus: %T", src)
	}
	return nil
}

type NullBatchStatus struct {
	BatchStatus BatchStatus `json:"BatchStatus"`
	Valid       bool        `json:"valid"` // Valid is true if BatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchStatus), nil
}

type CampaignStatus string

const (
	CampaignStatusACTIVE CampaignStatus = "ACTIVE"
	CampaignStatusPAUSED CampaignStatus = "PAUSED"
	CampaignStatusENDED  CampaignStatus = "ENDED"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"CampaignStatus"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type CapType string

const (
	CapTypeSLOTSXPRICE CapType = "SLOTS_X_PRICE"
	CapTypePOOL        CapType = "POOL"
)

func (e *CapType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CapType(s)
	case string:
		*e = CapType(s)
	default:
		return fmt.Errorf("unsupported scan type for CapType: %T", src)
	}
	return nil
}

type NullCapType struct {
	CapType CapType `json:"CapType"`
	Valid   bool    `json:"valid"` // Valid is true if CapType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCapType) Scan(value interface{}) error {
	if value == nil {
		ns.CapType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CapType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCapType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CapType), nil
}

type EarningStatus string

const (
	EarningStatusPENDING   EarningStatus = "PENDING"
	EarningStatusAVAILABLE EarningStatus = "AVAILABLE"
	EarningStatusPAID      EarningStatus = "PAID"
	EarningStatusREVERSED  EarningStatus = "REVERSED"
)

func (e *EarningStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EarningStatus(s)
	case string:
		*e = EarningStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EarningStatus: %T", src)
	}
	return nil
}

type NullEarningStatus struct {
	EarningStatus EarningStatus `json:"EarningStatus"`
	Valid         bool          `json:"valid"` // Valid is true if EarningStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEarningStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EarningStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EarningStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEarningStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EarningStatus), nil
}

type KycCaseState string

const (
	KycCaseStateDRAFT       KycCaseState = "DRAFT"
	KycCaseStateSUBMITTED   KycCaseState = "SUBMITTED"
	KycCaseStateRESUBMITTED KycCaseState = "RESUBMITTED"
	KycCaseStateAPPROVED    KycCaseState = "APPROVED"
	KycCaseStateREJECTED    KycCaseState = "REJECTED"
)

func (e *KycCaseState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycCaseState(s)
	case string:
		*e = KycCaseState(s)
	default:
		return fmt.Errorf("unsupported scan type for KycCaseState: %T", src)
	}
	return nil
}

type NullKycCaseState struct {
	KycCaseState KycCaseState `json:"KycCaseState"`
	Valid        bool         `json:"valid"` // Valid is true if KycCaseState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycCaseState) Scan(value interface{}) error {
	if value == nil {
		ns.KycCaseState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycCaseState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycCaseState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycCaseState), nil
}

type KycFieldState string

const (
	KycFieldStateEMPTY        KycFieldState = "EMPTY"
	KycFieldStateFILLED       KycFieldState = "FILLED"
	KycFieldStateACCEPTED     KycFieldState = "ACCEPTED"
	KycFieldStateNEEDSCHANGES KycFieldState = "NEEDS_CHANGES"
)

func (e *KycFieldState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycFieldState(s)
	case string:
		*e = KycFieldState(s)
	default:
		return fmt.Errorf("unsupported scan type for KycFieldState: %T", src)
	}
	return nil
}

type NullKycFieldState struct {
	KycFieldState KycFieldState `json:"KycFieldState"`
	Valid         bool          `json:"valid"` // Valid is true if KycFieldState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycFieldState) Scan(value interface{}) error {
	if value == nil {
		ns.KycFieldState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycFieldState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycFieldState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycFieldState), nil
}

type LedgerEntryType string

const (
	LedgerEntryTypeEARNINGACCRUE LedgerEntryType = "EARNING_ACCRUE"
	LedgerEntryTypeTAX           LedgerEntryType = "TAX"
	LedgerEntryTypePAYOUTRESERVE LedgerEntryType = "PAYOUT_RESERVE"
	LedgerEntryTypePAYOUTPAID    LedgerEntryType = "PAYOUT_PAID"
	LedgerEntryTypePAYOUTRELEASE LedgerEntryType = "PAYOUT_RELEASE"
	LedgerEntryTypeREVERSAL      LedgerEntryType = "REVERSAL"
)

func (e *LedgerEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntryType(s)
	case string:
		*e = LedgerEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntryType: %T", src)
	}
	return nil
}

type NullLedgerEntryType struct {
	LedgerEntryType LedgerEntryType `json:"LedgerEntryType"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntryType), nil
}

type OtpPurpose string

const (
	OtpPurposePAYOUT OtpPurpose = "PAYOUT"
)

func (e *OtpPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OtpPurpose(s)
	case string:
		*e = OtpPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for OtpPurpose: %T", src)
	}
	return nil
}

type NullOtpPurpose struct {
	OtpPurpose OtpPurpose `json:"OtpPurpose"`
	Valid      bool       `json:"valid"` // Valid is true if OtpPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOtpPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.OtpPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OtpPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOtpPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OtpPurpose), nil
}

type ParticipationState string

const (
	ParticipationStateJOINED           ParticipationState = "JOINED"
	ParticipationStateCONTENTSUBMITTED ParticipationState = "CONTENT_SUBMITTED"
	ParticipationStateAPPROVED         ParticipationState = "APPROVED"
	ParticipationStateREJECTED         ParticipationState = "REJECTED"
	ParticipationStateLEFT             ParticipationState = "LEFT"
	ParticipationStateEXPIRED          ParticipationState = "EXPIRED"
	ParticipationStateWAITLISTED       ParticipationState = "WAITLISTED"
)

func (e *ParticipationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipationState(s)
	case string:
		*e = ParticipationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipationState: %T", src)
	}
	return nil
}

type NullParticipationState struct {
	ParticipationState ParticipationState `json:"ParticipationState"`
	Valid              bool               `json:"valid"` // Valid is true if ParticipationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipationState) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipationState), nil
}

type PayoutAttemptResult string

const (
	PayoutAttemptResultSUCCESS PayoutAttemptResult = "SUCCESS"
	PayoutAttemptResultFAIL    PayoutAttemptResult = "FAIL"
	PayoutAttemptResultUNKNOWN PayoutAttemptResult = "UNKNOWN"
)

func (e *PayoutAttemptResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutAttemptResult(s)
	case string:
		*e = PayoutAttemptResult(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutAttemptResult: %T", src)
	}
	return nil
}

type NullPayoutAttemptResult struct {
	PayoutAttemptResult PayoutAttemptResult `json:"PayoutAttemptResult"`
	Valid               bool                `json:"valid"` // Valid is true if PayoutAttemptResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutAttemptResult) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutAttemptResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutAttemptResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutAttemptResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutAttemptResult), nil
}

type PayoutState string

const (
	PayoutStatePROCESSING     PayoutState = "PROCESSING"
	PayoutStatePAID           PayoutState = "PAID"
	PayoutStateFAILEDRELEASED PayoutState = "FAILED_RELEASED"
	PayoutStateUNKNOWNHOLD    PayoutState = "UNKNOWN_HOLD"
)

func (e *PayoutState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutState(s)
	case string:
		*e = PayoutState(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutState: %T", src)
	}
	return nil
}

type NullPayoutState struct {
	PayoutState PayoutState `json:"PayoutState"`
	Valid       bool        `json:"valid"` // Valid is true if PayoutState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutState) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutState), nil
}

type PricingType string

const (
	PricingTypeFLAT    PricingType = "FLAT"
	PricingTypeTIERED  PricingType = "TIERED"
	PricingTypePERCENT PricingType = "PERCENT"
)

func (e *PricingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingType(s)
	case string:
		*e = PricingType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingType: %T", src)
	}
	return nil
}

type NullPricingType struct {
	PricingType PricingType `json:"PricingType"`
	Valid       bool        `json:"valid"` // Valid is true if PricingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingType), nil
}

type RoleCode string

const (
	RoleCodeLOCALOPS     RoleCode = "LOCAL_OPS"
	RoleCodeLOCALFINANCE RoleCode = "LOCAL_FINANCE"
	RoleCodeLOCALADMIN   RoleCode = "LOCAL_ADMIN"
	RoleCodeGLOBALADMIN  RoleCode = "GLOBAL_ADMIN"
)

func (e *RoleCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleCode(s)
	case string:
		*e = RoleCode(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleCode: %T", src)
	}
	return nil
}

type NullRoleCode struct {
	RoleCode RoleCode `json:"RoleCode"`
	Valid    bool     `json:"valid"` // Valid is true if RoleCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleCode) Scan(value interface{}) error {
	if value == nil {
		ns.RoleCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleCode), nil
}

type SubmissionState string

const (
	SubmissionStateSUBMITTED SubmissionState = "SUBMITTED"
	SubmissionStateAPPROVED  SubmissionState = "APPROVED"
	SubmissionStateREJECTED  SubmissionState = "REJECTED"
)

func (e *SubmissionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionState(s)
	case string:
		*e = SubmissionState(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionState: %T", src)
	}
	return nil
}

type NullSubmissionState struct {
	SubmissionState SubmissionState `json:"SubmissionState"`
	Valid           bool            `json:"valid"` // Valid is true if SubmissionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionState) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionState), nil
}

type TriggerType string

const (
	TriggerTypeCONTENTAPPROVED TriggerType = "CONTENT_APPROVED"
	TriggerTypeVIEWTHRESHOLD   TriggerType = "VIEW_THRESHOLD"
	TriggerTypePAIDORDER       TriggerType = "PAID_ORDER"
)

func (e *TriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerType(s)
	case string:
		*e = TriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerType: %T", src)
	}
	return nil
}

type NullTriggerType struct {
	TriggerType TriggerType `json:"TriggerType"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerType), nil
}

type AppUser struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	AuthProvider    string             `json:"auth_provider"`
	ProviderSubject string             `json:"provider_subject"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	CountryID   pgtype.UUID        `json:"country_id"`
	Action      string             `json:"action"`
	TargetType  pgtype.Text        `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID              pgtype.UUID        `json:"id"`
	CountryID       pgtype.UUID        `json:"country_id"`
	Brand           string             `json:"brand"`
	Title           string             `json:"title"`
	RewardMinor     int64              `json:"reward_minor"`
	Currency        string             `json:"currency"`
	SlotsTotal      int32              `json:"slots_total"`
	SlotsTaken      int32              `json:"slots_taken"`
	Status          CampaignStatus     `json:"status"`
	Platform        string             `json:"platform"`
	RequiredHashtag string             `json:"required_hashtag"`
	Brief           string             `json:"brief"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
}

type ContentSubmission struct {
	ID              pgtype.UUID        `json:"id"`
	ParticipationID pgtype.UUID        `json:"participation_id"`
	AttemptNo       int32              `json:"attempt_no"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
	Url             string             `json:"url"`
	Platform        string             `json:"platform"`
	HashtagOk       bool               `json:"hashtag_ok"`
	PlatformOk      bool               `json:"platform_ok"`
	State           SubmissionState    `json:"state"`
	RejectReason    pgtype.Text        `json:"reject_reason"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RowVersion      int32              `json:"row_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Country struct {
	ID               pgtype.UUID        `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	CurrencyCode     string             `json:"currency_code"`
	CurrencyExponent int16              `json:"currency_exponent"`
	Locale           string             `json:"locale"`
	FallbackLocale   string             `json:"fallback_locale"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CountryConfig struct {
	ID             pgtype.UUID        `json:"id"`
	CountryID      pgtype.UUID        `json:"country_id"`
	TaxPercent     int32              `json:"tax_percent"`
	MinPayoutMinor int64              `json:"min_payout_minor"`
	FeatureKyc     bool               `json:"feature_kyc"`
	FeaturePayout  bool               `json:"feature_payout"`
	FeatureCps     bool               `json:"feature_cps"`
	ConfigVersion  int32              `json:"config_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CreatorCountryProfile struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CountryID       pgtype.UUID        `json:"country_id"`
	OnboardingState string             `json:"onboarding_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Earning struct {
	ID              pgtype.UUID        `json:"id"`
	ParticipationID pgtype.UUID        `json:"participation_id"`
	SubmissionID    pgtype.UUID        `json:"submission_id"`
	CountryID       pgtype.UUID        `json:"country_id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	GrossMinor      int64              `json:"gross_minor"`
	TaxMinor        int64              `json:"tax_minor"`
	Currency        string             `json:"currency"`
	Status          EarningStatus      `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type KycCase struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	State      KycCaseState       `json:"state"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type KycField struct {
	ID     pgtype.UUID   `json:"id"`
	CaseID pgtype.UUID   `json:"case_id"`
	Key    string        `json:"key"`
	Label  string        `json:"label"`
	Value  pgtype.Text   `json:"value"`
	State  KycFieldState `json:"state"`
	Reason pgtype.Text   `json:"reason"`
}

type LedgerEntry struct {
	ID           pgtype.UUID        `json:"id"`
	CountryID    pgtype.UUID        `json:"country_id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EntryType    LedgerEntryType    `json:"entry_type"`
	AmountMinor  int64              `json:"amount_minor"`
	Currency     string             `json:"currency"`
	RefType      string             `json:"ref_type"`
	RefID        pgtype.UUID        `json:"ref_id"`
	ReversalOfID pgtype.UUID        `json:"reversal_of_id"`
	EarningID    pgtype.UUID        `json:"earning_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Purpose    OtpPurpose         `json:"purpose"`
	Code       string             `json:"code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Participation struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	CampaignID          pgtype.UUID        `json:"campaign_id"`
	CountryID           pgtype.UUID        `json:"country_id"`
	State               ParticipationState `json:"state"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	SnapshotRewardMinor pgtype.Int8        `json:"snapshot_reward_minor"`
	SnapshotCurrency    pgtype.Text        `json:"snapshot_currency"`
	SnapshotTriggerType NullTriggerType    `json:"snapshot_trigger_type"`
	SnapshotPricingType NullPricingType    `json:"snapshot_pricing_type"`
	RowVersion          int32              `json:"row_version"`
	FixDeadlineAt       pgtype.Timestamptz `json:"fix_deadline_at"`
	StrikeCount         int32              `json:"strike_count"`
	SubmitDeadlineAt    pgtype.Timestamptz `json:"submit_deadline_at"`
	WaitlistedAt        pgtype.Timestamptz `json:"waitlisted_at"`
}

type PayoutAttempt struct {
	ID              pgtype.UUID         `json:"id"`
	PayoutRequestID pgtype.UUID         `json:"payout_request_id"`
	ProviderRef     string              `json:"provider_ref"`
	Result          PayoutAttemptResult `json:"result"`
	Raw             pgtype.Text         `json:"raw"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
}

type PayoutRequest struct {
	ID             pgtype.UUID        `json:"id"`
	CountryID      pgtype.UUID        `json:"country_id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	State          PayoutState        `json:"state"`
	OtpID          pgtype.UUID        `json:"otp_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
}

type ReconciliationBatch struct {
	ID        pgtype.UUID        `json:"id"`
	CountryID pgtype.UUID        `json:"country_id"`
	Period    string             `json:"period"`
	Status    BatchStatus        `json:"status"`
	LockedBy  pgtype.UUID        `json:"locked_by"`
	LockedAt  pgtype.Timestamptz `json:"locked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationLine struct {
	ID        pgtype.UUID        `json:"id"`
	BatchID   pgtype.UUID        `json:"batch_id"`
	EarningID pgtype.UUID        `json:"earning_id"`
	NetMinor  int64              `json:"net_minor"`
	Currency  string             `json:"currency"`
	Anomaly   pgtype.Text        `json:"anomaly"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RewardRule struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	TriggerType     TriggerType        `json:"trigger_type"`
	ViewThreshold   pgtype.Int4        `json:"view_threshold"`
	PricingType     PricingType        `json:"pricing_type"`
	FlatAmountMinor pgtype.Int8        `json:"flat_amount_minor"`
	PercentBps      pgtype.Int4        `json:"percent_bps"`
	CapType         CapType            `json:"cap_type"`
	CapSlots        pgtype.Int4        `json:"cap_slots"`
	CapPoolMinor    pgtype.Int8        `json:"cap_pool_minor"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RoleAssignment struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CountryID pgtype.UUID        `json:"country_id"`
	Role      RoleCode           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
