// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPayoutState = `-- name: ClaimPayoutState :one
UPDATE payout_request
SET state = $1::"PayoutState"
WHERE id = $2 AND state = $3::"PayoutState"
RETURNING id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key, requested_at
`

type ClaimPayoutStateParams struct {
	ToState   PayoutState `json:"to_state"`
	ID        pgtype.UUID `json:"id"`
	FromState PayoutState `json:"from_state"`
}

func (q *Queries) ClaimPayoutState(ctx context.Context, arg ClaimPayoutStateParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, claimPayoutState, arg.ToState, arg.ID, arg.FromState)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.ProfileID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.OtpID,
		&i.IdempotencyKey,
		&i.RequestedAt,
	)
	return i, err
}

const consumePayoutOTP = `-- name: ConsumePayoutOTP :one
UPDATE otp_code
SET consumed_at = CURRENT_TIMESTAMP
WHERE id = $1 AND consumed_at IS NULL
RETURNING id, user_id, purpose, code, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumePayoutOTP(ctx context.Context, id pgtype.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, consumePayoutOTP, id)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Code,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPayoutAttempt = `-- name: CreatePayoutAttempt :one
INSERT INTO payout_attempt (id, payout_request_id, provider_ref, result, raw)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, payout_request_id, provider_ref, result, raw, created_at
`

type CreatePayoutAttemptParams struct {
	ID              pgtype.UUID         `json:"id"`
	PayoutRequestID pgtype.UUID         `json:"payout_request_id"`
	ProviderRef     string              `json:"provider_ref"`
	Result          PayoutAttemptResult `json:"result"`
	Raw             pgtype.Text         `json:"raw"`
}

func (q *Queries) CreatePayoutAttempt(ctx context.Context, arg CreatePayoutAttemptParams) (PayoutAttempt, error) {
	row := q.db.QueryRow(ctx, createPayoutAttempt,
		arg.ID,
		arg.PayoutRequestID,
		arg.ProviderRef,
		arg.Result,
		arg.Raw,
	)
	var i PayoutAttempt
	err := row.Scan(
		&i.ID,
		&i.PayoutRequestID,
		&i.ProviderRef,
		&i.Result,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const createPayoutOTP = `-- name: CreatePayoutOTP :one
INSERT INTO otp_code (id, user_id, purpose, code, expires_at)
VALUES ($1, $2, 'PAYOUT', $3, $4)
RETURNING id, user_id, purpose, code, expires_at, consumed_at, created_at
`

type CreatePayoutOTPParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePayoutOTP(ctx context.Context, arg CreatePayoutOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createPayoutOTP,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Code,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPayoutRequest = `-- name: CreatePayoutRequest :one
INSERT INTO payout_request (
  id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, 'PROCESSING', $6, $7)
RETURNING id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key, requested_at
`

type CreatePayoutRequestParams struct {
	ID             pgtype.UUID `json:"id"`
	CountryID      pgtype.UUID `json:"country_id"`
	ProfileID      pgtype.UUID `json:"profile_id"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       string      `json:"currency"`
	OtpID          pgtype.UUID `json:"otp_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, createPayoutRequest,
		arg.ID,
		arg.CountryID,
		arg.ProfileID,
		arg.AmountMinor,
		arg.Currency,
		arg.OtpID,
		arg.IdempotencyKey,
	)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.ProfileID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.OtpID,
		&i.IdempotencyKey,
		&i.RequestedAt,
	)
	return i, err
}

const getPayoutByIdempotencyKey = `-- name: GetPayoutByIdempotencyKey :one
SELECT id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key, requested_at
FROM payout_request
WHERE idempotency_key = $1 AND profile_id = $2
`

type GetPayoutByIdempotencyKeyParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	ProfileID      pgtype.UUID `json:"profile_id"`
}

func (q *Queries) GetPayoutByIdempotencyKey(ctx context.Context, arg GetPayoutByIdempotencyKeyParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, getPayoutByIdempotencyKey, arg.IdempotencyKey, arg.ProfileID)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.ProfileID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.OtpID,
		&i.IdempotencyKey,
		&i.RequestedAt,
	)
	return i, err
}

const getPayoutInCountry = `-- name: GetPayoutInCountry :one
SELECT id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key, requested_at
FROM payout_request
WHERE id = $1 AND country_id = $2
`

type GetPayoutInCountryParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) GetPayoutInCountry(ctx context.Context, arg GetPayoutInCountryParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, getPayoutInCountry, arg.ID, arg.CountryID)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.ProfileID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.OtpID,
		&i.IdempotencyKey,
		&i.RequestedAt,
	)
	return i, err
}

const getPayoutOTPForUpdate = `-- name: GetPayoutOTPForUpdate :one
SELECT id, user_id, purpose, code, expires_at, consumed_at, created_at
FROM otp_code
WHERE id = $1 AND user_id = $2 AND purpose = 'PAYOUT'
FOR UPDATE
`

type GetPayoutOTPForUpdateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPayoutOTPForUpdate(ctx context.Context, arg GetPayoutOTPForUpdateParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getPayoutOTPForUpdate, arg.ID, arg.UserID)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Code,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutQueueByState = `-- name: ListPayoutQueueByState :many
SELECT
  payout.id, payout.country_id, payout.profile_id, payout.amount_minor, payout.currency, payout.state, payout.otp_id, payout.idempotency_key, payout.requested_at,
  u.display_name AS creator_name
FROM payout_request payout
JOIN creator_country_profile profile ON profile.id = payout.profile_id
JOIN app_user u ON u.id = profile.user_id
WHERE payout.country_id = $1 AND payout.state = $2
ORDER BY payout.requested_at ASC, payout.id ASC
`

type ListPayoutQueueByStateParams struct {
	CountryID pgtype.UUID `json:"country_id"`
	State     PayoutState `json:"state"`
}

type ListPayoutQueueByStateRow struct {
	ID             pgtype.UUID        `json:"id"`
	CountryID      pgtype.UUID        `json:"country_id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	State          PayoutState        `json:"state"`
	OtpID          pgtype.UUID        `json:"otp_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
	CreatorName    string             `json:"creator_name"`
}

func (q *Queries) ListPayoutQueueByState(ctx context.Context, arg ListPayoutQueueByStateParams) ([]ListPayoutQueueByStateRow, error) {
	rows, err := q.db.Query(ctx, listPayoutQueueByState, arg.CountryID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayoutQueueByStateRow
	for rows.Next() {
		var i ListPayoutQueueByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.ProfileID,
			&i.AmountMinor,
			&i.Currency,
			&i.State,
			&i.OtpID,
			&i.IdempotencyKey,
			&i.RequestedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilePayouts = `-- name: ListProfilePayouts :many
SELECT id, country_id, profile_id, amount_minor, currency, state, otp_id, idempotency_key, requested_at
FROM payout_request
WHERE profile_id = $1 AND country_id = $2
ORDER BY requested_at DESC, id DESC
`

type ListProfilePayoutsParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) ListProfilePayouts(ctx context.Context, arg ListProfilePayoutsParams) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listProfilePayouts, arg.ProfileID, arg.CountryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.ProfileID,
			&i.AmountMinor,
			&i.Currency,
			&i.State,
			&i.OtpID,
			&i.IdempotencyKey,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreatorProfileForPayout = `-- name: LockCreatorProfileForPayout :one
SELECT id
FROM creator_country_profile
WHERE id = $1 AND country_id = $2
FOR UPDATE
`

type LockCreatorProfileForPayoutParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) LockCreatorProfileForPayout(ctx context.Context, arg LockCreatorProfileForPayoutParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockCreatorProfileForPayout, arg.ID, arg.CountryID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const nextPayoutAttemptNo = `-- name: NextPayoutAttemptNo :one
SELECT (count(*) + 1)::integer
FROM payout_attempt
WHERE payout_request_id = $1
`

func (q *Queries) NextPayoutAttemptNo(ctx context.Context, payoutRequestID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPayoutAttemptNo, payoutRequestID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const sumAvailableEarningNet = `-- name: SumAvailableEarningNet :one
SELECT COALESCE(sum(gross_minor - tax_minor), 0)::bigint
FROM earning
WHERE profile_id = $1 AND country_id = $2 AND status = 'AVAILABLE'
`

type SumAvailableEarningNetParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) SumAvailableEarningNet(ctx context.Context, arg SumAvailableEarningNetParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumAvailableEarningNet, arg.ProfileID, arg.CountryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumOutstandingPayouts = `-- name: SumOutstandingPayouts :one
SELECT COALESCE(sum(amount_minor), 0)::bigint
FROM payout_request
WHERE profile_id = $1 AND country_id = $2
  AND state IN ('PROCESSING', 'PAID', 'UNKNOWN_HOLD')
`

type SumOutstandingPayoutsParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	CountryID pgtype.UUID `json:"country_id"`
}

func (q *Queries) SumOutstandingPayouts(ctx context.Context, arg SumOutstandingPayoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumOutstandingPayouts, arg.ProfileID, arg.CountryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
