// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AllKycFieldsAccepted(ctx context.Context, caseID pgtype.UUID) (bool, error)
	// The conditional state predicate is the review claim: under concurrent approvals only one
	// transaction can return a row. The loser observes zero rows after the winner commits.
	ClaimContentReview(ctx context.Context, arg ClaimContentReviewParams) (ContentSubmission, error)
	ClaimPayoutState(ctx context.Context, arg ClaimPayoutStateParams) (PayoutRequest, error)
	ClaimReconciliationBatchLock(ctx context.Context, arg ClaimReconciliationBatchLockParams) (ReconciliationBatch, error)
	ConsumePayoutOTP(ctx context.Context, id pgtype.UUID) (OtpCode, error)
	CountWaitlistAhead(ctx context.Context, arg CountWaitlistAheadParams) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateContentSubmission(ctx context.Context, arg CreateContentSubmissionParams) (ContentSubmission, error)
	CreateEarning(ctx context.Context, arg CreateEarningParams) (Earning, error)
	CreateJoinedParticipation(ctx context.Context, arg CreateJoinedParticipationParams) (Participation, error)
	CreateKycField(ctx context.Context, arg CreateKycFieldParams) error
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreatePayoutAttempt(ctx context.Context, arg CreatePayoutAttemptParams) (PayoutAttempt, error)
	CreatePayoutOTP(ctx context.Context, arg CreatePayoutOTPParams) (OtpCode, error)
	CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error)
	CreateReconciliationBatch(ctx context.Context, arg CreateReconciliationBatchParams) (ReconciliationBatch, error)
	CreateReconciliationLine(ctx context.Context, arg CreateReconciliationLineParams) (ReconciliationLine, error)
	CreateRewardRule(ctx context.Context, arg CreateRewardRuleParams) (RewardRule, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateWaitlistedParticipation(ctx context.Context, arg CreateWaitlistedParticipationParams) (Participation, error)
	DecrementCampaignSlots(ctx context.Context, id pgtype.UUID) error
	ExpireParticipation(ctx context.Context, id pgtype.UUID) (Participation, error)
	FinishKycReview(ctx context.Context, arg FinishKycReviewParams) (KycCase, error)
	GetCampaignForCountry(ctx context.Context, arg GetCampaignForCountryParams) (Campaign, error)
	GetCountryByCode(ctx context.Context, code string) (Country, error)
	GetCountryConfigByCountryID(ctx context.Context, countryID pgtype.UUID) (CountryConfig, error)
	GetKycCaseByID(ctx context.Context, id pgtype.UUID) (KycCase, error)
	GetKycCaseForCountry(ctx context.Context, id pgtype.UUID) (GetKycCaseForCountryRow, error)
	GetKycStateForProfile(ctx context.Context, profileID pgtype.UUID) (KycCaseState, error)
	GetLatestRejectedSubmission(ctx context.Context, participationID pgtype.UUID) (ContentSubmission, error)
	GetNextWaitlistedParticipation(ctx context.Context, campaignID pgtype.UUID) (Participation, error)
	GetParticipationByID(ctx context.Context, id pgtype.UUID) (Participation, error)
	GetParticipationForContent(ctx context.Context, arg GetParticipationForContentParams) (GetParticipationForContentRow, error)
	GetParticipationForJoin(ctx context.Context, arg GetParticipationForJoinParams) (Participation, error)
	GetPayoutByIdempotencyKey(ctx context.Context, arg GetPayoutByIdempotencyKeyParams) (PayoutRequest, error)
	GetPayoutInCountry(ctx context.Context, arg GetPayoutInCountryParams) (PayoutRequest, error)
	GetPayoutOTPForUpdate(ctx context.Context, arg GetPayoutOTPForUpdateParams) (OtpCode, error)
	GetReconciliationBatch(ctx context.Context, arg GetReconciliationBatchParams) (GetReconciliationBatchRow, error)
	GetRewardRuleByCampaignID(ctx context.Context, campaignID pgtype.UUID) (RewardRule, error)
	GetSessionUserByTokenHash(ctx context.Context, tokenHash string) (GetSessionUserByTokenHashRow, error)
	GetSubmissionForReviewCountry(ctx context.Context, arg GetSubmissionForReviewCountryParams) (GetSubmissionForReviewCountryRow, error)
	IncrementCampaignSlots(ctx context.Context, id pgtype.UUID) error
	LeaveParticipation(ctx context.Context, id pgtype.UUID) (Participation, error)
	ListActiveCampaignsByCountry(ctx context.Context, countryID pgtype.UUID) ([]Campaign, error)
	ListAuditEvents(ctx context.Context, dollar_1 pgtype.UUID) ([]ListAuditEventsRow, error)
	ListCampaignsByCountry(ctx context.Context, countryID pgtype.UUID) ([]Campaign, error)
	ListContentQueue(ctx context.Context, countryID pgtype.UUID) ([]ListContentQueueRow, error)
	ListContentSubmissions(ctx context.Context, participationID pgtype.UUID) ([]ContentSubmission, error)
	ListCreatorCountryProfiles(ctx context.Context, userID pgtype.UUID) ([]ListCreatorCountryProfilesRow, error)
	ListEarningsForDashboard(ctx context.Context, arg ListEarningsForDashboardParams) ([]ListEarningsForDashboardRow, error)
	ListExpiredParticipationCandidates(ctx context.Context, submitDeadlineAt pgtype.Timestamptz) ([]ListExpiredParticipationCandidatesRow, error)
	ListKycFields(ctx context.Context, caseID pgtype.UUID) ([]KycField, error)
	ListKycQueueCases(ctx context.Context, countryID pgtype.UUID) ([]ListKycQueueCasesRow, error)
	// Ledger rows created in one PostgreSQL transaction share CURRENT_TIMESTAMP. The type rank keeps
	// accrual before tax for a deterministic running balance, then falls back to UUID for total order.
	ListLedgerEntriesForProfile(ctx context.Context, arg ListLedgerEntriesForProfileParams) ([]LedgerEntry, error)
	ListMyParticipations(ctx context.Context, arg ListMyParticipationsParams) ([]ListMyParticipationsRow, error)
	ListPayoutQueueByState(ctx context.Context, arg ListPayoutQueueByStateParams) ([]ListPayoutQueueByStateRow, error)
	ListPendingUnreconciledEarnings(ctx context.Context, countryID pgtype.UUID) ([]Earning, error)
	ListProfilePayouts(ctx context.Context, arg ListProfilePayoutsParams) ([]PayoutRequest, error)
	ListReconciliationBatches(ctx context.Context, countryID pgtype.UUID) ([]ListReconciliationBatchesRow, error)
	ListReconciliationLines(ctx context.Context, batchID pgtype.UUID) ([]ListReconciliationLinesRow, error)
	ListRolesForUser(ctx context.Context, userID pgtype.UUID) ([]ListRolesForUserRow, error)
	LockCampaignForJoin(ctx context.Context, arg LockCampaignForJoinParams) (LockCampaignForJoinRow, error)
	LockCampaignForReclaim(ctx context.Context, id pgtype.UUID) (LockCampaignForReclaimRow, error)
	// Serializes batch creation per country so concurrent Finance requests cannot select the same
	// unbatched earnings before either inserts reconciliation lines.
	LockCountryForReconciliation(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockCreatorProfileForPayout(ctx context.Context, arg LockCreatorProfileForPayoutParams) (pgtype.UUID, error)
	LockParticipationForContent(ctx context.Context, arg LockParticipationForContentParams) (LockParticipationForContentRow, error)
	MarkParticipationApproved(ctx context.Context, id pgtype.UUID) error
	MarkParticipationContentSubmitted(ctx context.Context, id pgtype.UUID) error
	MarkParticipationRejected(ctx context.Context, arg MarkParticipationRejectedParams) error
	NextPayoutAttemptNo(ctx context.Context, payoutRequestID pgtype.UUID) (int32, error)
	NextSubmissionAttemptNo(ctx context.Context, participationID pgtype.UUID) (int32, error)
	// PostgreSQL stores waitlisted_at at millisecond precision. The campaign row lock serializes
	// callers; advancing at least one millisecond avoids tied timestamps and preserves strict FCFS.
	NextWaitlistedAt(ctx context.Context, campaignID pgtype.UUID) (pgtype.Timestamptz, error)
	Ping(ctx context.Context) (int64, error)
	ReleaseBatchEarnings(ctx context.Context, batchID pgtype.UUID) ([]pgtype.UUID, error)
	ReviewKycField(ctx context.Context, arg ReviewKycFieldParams) error
	RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error
	SubmitKycCase(ctx context.Context, id pgtype.UUID) (KycCase, error)
	SumAvailableEarningNet(ctx context.Context, arg SumAvailableEarningNetParams) (int64, error)
	SumOutstandingPayouts(ctx context.Context, arg SumOutstandingPayoutsParams) (int64, error)
	UpdateEditableKycField(ctx context.Context, arg UpdateEditableKycFieldParams) error
	UpdateJoinedParticipation(ctx context.Context, arg UpdateJoinedParticipationParams) (Participation, error)
	UpdateWaitlistedParticipation(ctx context.Context, arg UpdateWaitlistedParticipationParams) (Participation, error)
	UpsertCreatorCountryProfile(ctx context.Context, arg UpsertCreatorCountryProfileParams) (CreatorCountryProfile, error)
	UpsertKycCase(ctx context.Context, arg UpsertKycCaseParams) (KycCase, error)
	UpsertMockUser(ctx context.Context, arg UpsertMockUserParams) (AppUser, error)
}

var _ Querier = (*Queries)(nil)
