// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimReconciliationBatchLock = `-- name: ClaimReconciliationBatchLock :one
UPDATE reconciliation_batch
SET status = 'LOCKED', locked_by = $2, locked_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'OPEN'
RETURNING id, country_id, period, status, locked_by, locked_at, created_at
`

type ClaimReconciliationBatchLockParams struct {
	ID       pgtype.UUID `json:"id"`
	LockedBy pgtype.UUID `json:"locked_by"`
}

func (q *Queries) ClaimReconciliationBatchLock(ctx context.Context, arg ClaimReconciliationBatchLockParams) (ReconciliationBatch, error) {
	row := q.db.QueryRow(ctx, claimReconciliationBatchLock, arg.ID, arg.LockedBy)
	var i ReconciliationBatch
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Period,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReconciliationBatch = `-- name: CreateReconciliationBatch :one
INSERT INTO reconciliation_batch (id, country_id, period, status)
VALUES ($1, $2, $3, 'OPEN')
RETURNING id, country_id, period, status, locked_by, locked_at, created_at
`

type CreateReconciliationBatchParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
	Period    string      `json:"period"`
}

func (q *Queries) CreateReconciliationBatch(ctx context.Context, arg CreateReconciliationBatchParams) (ReconciliationBatch, error) {
	row := q.db.QueryRow(ctx, createReconciliationBatch, arg.ID, arg.CountryID, arg.Period)
	var i ReconciliationBatch
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Period,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReconciliationLine = `-- name: CreateReconciliationLine :one
INSERT INTO reconciliation_line (id, batch_id, earning_id, net_minor, currency, anomaly)
VALUES ($1, $2, $3, $4, $5, NULL)
RETURNING id, batch_id, earning_id, net_minor, currency, anomaly, created_at
`

type CreateReconciliationLineParams struct {
	ID        pgtype.UUID `json:"id"`
	BatchID   pgtype.UUID `json:"batch_id"`
	EarningID pgtype.UUID `json:"earning_id"`
	NetMinor  int64       `json:"net_minor"`
	Currency  string      `json:"currency"`
}

func (q *Queries) CreateReconciliationLine(ctx context.Context, arg CreateReconciliationLineParams) (ReconciliationLine, error) {
	row := q.db.QueryRow(ctx, createReconciliationLine,
		arg.ID,
		arg.BatchID,
		arg.EarningID,
		arg.NetMinor,
		arg.Currency,
	)
	var i ReconciliationLine
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EarningID,
		&i.NetMinor,
		&i.Currency,
		&i.Anomaly,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliationBatch = `-- name: GetReconciliationBatch :one
SELECT
  b.id,
  b.period,
  b.status,
  b.locked_at,
  count(l.id)::bigint AS line_count,
  COALESCE(sum(CASE WHEN l.anomaly IS NULL THEN l.net_minor ELSE 0 END), 0)::bigint AS total_net_minor,
  (array_agg(l.currency ORDER BY l.created_at, l.id) FILTER (WHERE l.id IS NOT NULL))[1] AS currency
FROM reconciliation_batch b
LEFT JOIN reconciliation_line l ON l.batch_id = b.id
WHERE b.id = $1 AND b.country_id = $2
GROUP BY b.id
`

type GetReconciliationBatchParams struct {
	ID        pgtype.UUID `json:"id"`
	CountryID pgtype.UUID `json:"country_id"`
}

type GetReconciliationBatchRow struct {
	ID            pgtype.UUID        `json:"id"`
	Period        string             `json:"period"`
	Status        BatchStatus        `json:"status"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LineCount     int64              `json:"line_count"`
	TotalNetMinor int64              `json:"total_net_minor"`
	Currency      interface{}        `json:"currency"`
}

func (q *Queries) GetReconciliationBatch(ctx context.Context, arg GetReconciliationBatchParams) (GetReconciliationBatchRow, error) {
	row := q.db.QueryRow(ctx, getReconciliationBatch, arg.ID, arg.CountryID)
	var i GetReconciliationBatchRow
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.Status,
		&i.LockedAt,
		&i.LineCount,
		&i.TotalNetMinor,
		&i.Currency,
	)
	return i, err
}

const listPendingUnreconciledEarnings = `-- name: ListPendingUnreconciledEarnings :many
SELECT e.id, e.participation_id, e.submission_id, e.country_id, e.profile_id, e.gross_minor, e.tax_minor, e.currency, e.status, e.created_at, e.updated_at
FROM earning e
LEFT JOIN reconciliation_line l ON l.earning_id = e.id
WHERE e.country_id = $1 AND e.status = 'PENDING' AND l.id IS NULL
ORDER BY e.created_at ASC, e.id ASC
`

func (q *Queries) ListPendingUnreconciledEarnings(ctx context.Context, countryID pgtype.UUID) ([]Earning, error) {
	rows, err := q.db.Query(ctx, listPendingUnreconciledEarnings, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.SubmissionID,
			&i.CountryID,
			&i.ProfileID,
			&i.GrossMinor,
			&i.TaxMinor,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationBatches = `-- name: ListReconciliationBatches :many
SELECT
  b.id,
  b.period,
  b.status,
  b.locked_at,
  count(l.id)::bigint AS line_count,
  COALESCE(sum(CASE WHEN l.anomaly IS NULL THEN l.net_minor ELSE 0 END), 0)::bigint AS total_net_minor,
  (array_agg(l.currency ORDER BY l.created_at, l.id) FILTER (WHERE l.id IS NOT NULL))[1] AS currency
FROM reconciliation_batch b
LEFT JOIN reconciliation_line l ON l.batch_id = b.id
WHERE b.country_id = $1
GROUP BY b.id
ORDER BY b.created_at DESC, b.id DESC
`

type ListReconciliationBatchesRow struct {
	ID            pgtype.UUID        `json:"id"`
	Period        string             `json:"period"`
	Status        BatchStatus        `json:"status"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LineCount     int64              `json:"line_count"`
	TotalNetMinor int64              `json:"total_net_minor"`
	Currency      interface{}        `json:"currency"`
}

func (q *Queries) ListReconciliationBatches(ctx context.Context, countryID pgtype.UUID) ([]ListReconciliationBatchesRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationBatches, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconciliationBatchesRow
	for rows.Next() {
		var i ListReconciliationBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.Status,
			&i.LockedAt,
			&i.LineCount,
			&i.TotalNetMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationLines = `-- name: ListReconciliationLines :many
SELECT
  l.id,
  l.earning_id,
  u.display_name AS creator_name,
  c.title AS campaign_title,
  l.net_minor,
  l.currency,
  l.anomaly
FROM reconciliation_line l
JOIN earning e ON e.id = l.earning_id
JOIN creator_country_profile p ON p.id = e.profile_id
JOIN app_user u ON u.id = p.user_id
JOIN participation participation ON participation.id = e.participation_id
JOIN campaign c ON c.id = participation.campaign_id
WHERE l.batch_id = $1
ORDER BY l.created_at ASC, l.id ASC
`

type ListReconciliationLinesRow struct {
	ID            pgtype.UUID `json:"id"`
	EarningID     pgtype.UUID `json:"earning_id"`
	CreatorName   string      `json:"creator_name"`
	CampaignTitle string      `json:"campaign_title"`
	NetMinor      int64       `json:"net_minor"`
	Currency      string      `json:"currency"`
	Anomaly       pgtype.Text `json:"anomaly"`
}

func (q *Queries) ListReconciliationLines(ctx context.Context, batchID pgtype.UUID) ([]ListReconciliationLinesRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationLines, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconciliationLinesRow
	for rows.Next() {
		var i ListReconciliationLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.EarningID,
			&i.CreatorName,
			&i.CampaignTitle,
			&i.NetMinor,
			&i.Currency,
			&i.Anomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCountryForReconciliation = `-- name: LockCountryForReconciliation :one
SELECT id
FROM country
WHERE id = $1
FOR UPDATE
`

// Serializes batch creation per country so concurrent Finance requests cannot select the same
// unbatched earnings before either inserts reconciliation lines.
func (q *Queries) LockCountryForReconciliation(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockCountryForReconciliation, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const releaseBatchEarnings = `-- name: ReleaseBatchEarnings :many
UPDATE earning e
SET status = 'AVAILABLE', updated_at = CURRENT_TIMESTAMP
FROM reconciliation_line l
WHERE l.batch_id = $1
  AND l.earning_id = e.id
  AND l.anomaly IS NULL
  AND e.status = 'PENDING'
RETURNING e.id
`

func (q *Queries) ReleaseBatchEarnings(ctx context.Context, batchID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, releaseBatchEarnings, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
